/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as ServicesWebsitesRouteImport } from './routes/services.websites'
import { Route as ServicesVoiceAgentsRouteImport } from './routes/services.voice-agents'
import { Route as ServicesSeoRouteImport } from './routes/services.seo'
import { Route as ServicesChatAgentsRouteImport } from './routes/services.chat-agents'
import { Route as ServicesAutomationRouteImport } from './routes/services.automation'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as ApiChatRouteImport } from './routes/api/chat'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ServicesRoute,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogRoute,
} as any)
const ServicesWebsitesRoute = ServicesWebsitesRouteImport.update({
  id: '/websites',
  path: '/websites',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesVoiceAgentsRoute = ServicesVoiceAgentsRouteImport.update({
  id: '/voice-agents',
  path: '/voice-agents',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesSeoRoute = ServicesSeoRouteImport.update({
  id: '/seo',
  path: '/seo',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesChatAgentsRoute = ServicesChatAgentsRouteImport.update({
  id: '/chat-agents',
  path: '/chat-agents',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesAutomationRoute = ServicesAutomationRouteImport.update({
  id: '/automation',
  path: '/automation',
  getParentRoute: () => ServicesRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/pricing': typeof PricingRoute
  '/services': typeof ServicesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/chat': typeof ApiChatRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/services/automation': typeof ServicesAutomationRoute
  '/services/chat-agents': typeof ServicesChatAgentsRoute
  '/services/seo': typeof ServicesSeoRoute
  '/services/voice-agents': typeof ServicesVoiceAgentsRoute
  '/services/websites': typeof ServicesWebsitesRoute
  '/blog/': typeof BlogIndexRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/pricing': typeof PricingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/chat': typeof ApiChatRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/services/automation': typeof ServicesAutomationRoute
  '/services/chat-agents': typeof ServicesChatAgentsRoute
  '/services/seo': typeof ServicesSeoRoute
  '/services/voice-agents': typeof ServicesVoiceAgentsRoute
  '/services/websites': typeof ServicesWebsitesRoute
  '/blog': typeof BlogIndexRoute
  '/services': typeof ServicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/pricing': typeof PricingRoute
  '/services': typeof ServicesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/chat': typeof ApiChatRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/services/automation': typeof ServicesAutomationRoute
  '/services/chat-agents': typeof ServicesChatAgentsRoute
  '/services/seo': typeof ServicesSeoRoute
  '/services/voice-agents': typeof ServicesVoiceAgentsRoute
  '/services/websites': typeof ServicesWebsitesRoute
  '/blog/': typeof BlogIndexRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/pricing'
    | '/services'
    | '/sitemap.xml'
    | '/api/chat'
    | '/blog/$slug'
    | '/services/automation'
    | '/services/chat-agents'
    | '/services/seo'
    | '/services/voice-agents'
    | '/services/websites'
    | '/blog/'
    | '/services/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/pricing'
    | '/sitemap.xml'
    | '/api/chat'
    | '/blog/$slug'
    | '/services/automation'
    | '/services/chat-agents'
    | '/services/seo'
    | '/services/voice-agents'
    | '/services/websites'
    | '/blog'
    | '/services'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/pricing'
    | '/services'
    | '/sitemap.xml'
    | '/api/chat'
    | '/blog/$slug'
    | '/services/automation'
    | '/services/chat-agents'
    | '/services/seo'
    | '/services/voice-agents'
    | '/services/websites'
    | '/blog/'
    | '/services/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BlogRoute: typeof BlogRouteWithChildren
  ContactRoute: typeof ContactRoute
  PricingRoute: typeof PricingRoute
  ServicesRoute: typeof ServicesRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiChatRoute: typeof ApiChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/blog/': {
      id: '/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof BlogRoute
    }
    '/services/websites': {
      id: '/services/websites'
      path: '/websites'
      fullPath: '/services/websites'
      preLoaderRoute: typeof ServicesWebsitesRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/voice-agents': {
      id: '/services/voice-agents'
      path: '/voice-agents'
      fullPath: '/services/voice-agents'
      preLoaderRoute: typeof ServicesVoiceAgentsRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/seo': {
      id: '/services/seo'
      path: '/seo'
      fullPath: '/services/seo'
      preLoaderRoute: typeof ServicesSeoRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/chat-agents': {
      id: '/services/chat-agents'
      path: '/chat-agents'
      fullPath: '/services/chat-agents'
      preLoaderRoute: typeof ServicesChatAgentsRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/automation': {
      id: '/services/automation'
      path: '/automation'
      fullPath: '/services/automation'
      preLoaderRoute: typeof ServicesAutomationRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface ServicesRouteChildren {
  ServicesAutomationRoute: typeof ServicesAutomationRoute
  ServicesChatAgentsRoute: typeof ServicesChatAgentsRoute
  ServicesSeoRoute: typeof ServicesSeoRoute
  ServicesVoiceAgentsRoute: typeof ServicesVoiceAgentsRoute
  ServicesWebsitesRoute: typeof ServicesWebsitesRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesAutomationRoute: ServicesAutomationRoute,
  ServicesChatAgentsRoute: ServicesChatAgentsRoute,
  ServicesSeoRoute: ServicesSeoRoute,
  ServicesVoiceAgentsRoute: ServicesVoiceAgentsRoute,
  ServicesWebsitesRoute: ServicesWebsitesRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BlogRoute: BlogRouteWithChildren,
  ContactRoute: ContactRoute,
  PricingRoute: PricingRoute,
  ServicesRoute: ServicesRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiChatRoute: ApiChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
